# Generated by Django 5.2.11 on 2026-02-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='category-images/image.png', upload_to='category-images/%Y/%m/%d/'),
        ),
    ]
